agents:
  queue: release
_templates:
  common: &common
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: -1
          limit: 10
        - exit_status: "*"
          limit: 2

env:
  # Force a clean checkout every time to avoid reuse of files between runs.
  BUILDKITE_CLEAN_CHECKOUT: true

steps:
  # GPU workflow.
  - <<: *common
    if: build.branch == "master" && build.tag == null
    label: ":screwdriver: All GPU Drivers Test"
    commands:
      - tools/gpu/all_drivers_test.sh
    agents:
      queue: gpu